import test from 'node:test';
import assert from 'node:assert/strict';
import {rubToByn,bynToRub,itemStats,shipmentStats,fifoAllocations,validateBackup} from '../lib/core.js';

function base(){return {factories:[],suppliers:[],expenses:[],compensations:[],audit:[],settings:{coefficient:40},shipments:[{id:'s1',date:'2026-01-01',receptionClosed:true}],items:[{id:'i1',shipmentId:'s1',name:'Женские штаны',orderedQty:30,purchaseMinor:2000}],movements:[{id:'r',itemId:'i1',type:'receipt',qty:27,date:'2026-01-02'},{id:'d',itemId:'i1',type:'defect',qty:2,date:'2026-01-02'},{id:'m',itemId:'i1',type:'sale',qty:10,date:'2026-01-03'}],sales:[{id:'x',date:'2026-01-03',qty:10,totalMinor:35000,revenueRubMinor:35000,cogsMinor:20000,shipmentIds:['s1']}],returns:[],meta:{schemaVersion:2}}}
test('контрольный сценарий',()=>{const d=base(),s=shipmentStats(d,'s1');assert.equal(s.shortage,3);assert.equal(s.defects,2);assert.equal(s.goodReceived,25);assert.equal(s.available,15);assert.equal(s.revenue,35000);assert.equal(s.cogs,20000);assert.equal(s.gross,15000);assert.equal(s.markup,'75%');assert.equal(s.margin,'42,86%');assert.equal(s.soldPercent,'40%')});
test('до закрытия это ожидание, а не недостача',()=>{const d=base();d.shipments[0].receptionClosed=false;const s=shipmentStats(d,'s1');assert.equal(s.shortage,0);assert.equal(s.expected,3)});
test('излишек',()=>{const d=base();d.movements[0].qty=35;const s=shipmentStats(d,'s1');assert.equal(s.surplus,5)});
test('пересчёт RUB/BYN точен',()=>{assert.equal(rubToByn(140000,40),5600);assert.equal(bynToRub(5699,40),142475)});
test('FIFO сохраняет цены партий',()=>{const d=base();d.shipments.push({id:'s2',date:'2026-02-01',receptionClosed:true});d.items.push({id:'i2',shipmentId:'s2',name:'Женские штаны',orderedQty:15,purchaseMinor:2500});d.movements.push({itemId:'i2',type:'receipt',qty:15,date:'2026-02-02'});const r=fifoAllocations(d,'Женские штаны',18);assert.equal(r.left,0);assert.equal(r.allocations[0].itemId,'i1');assert.equal(r.allocations[0].unitCostMinor,2000);assert.equal(r.allocations[1].unitCostMinor,2500)});
test('возврат и списание корректируют остаток',()=>{const d=base();d.movements.push({itemId:'i1',type:'customer_return',qty:2,date:'2026-01-04'},{itemId:'i1',type:'writeoff',qty:1,date:'2026-01-05'});assert.equal(itemStats(d,'i1').available,16)});
test('резервная копия проверяется',()=>{assert.equal(validateBackup(base()).ok,true);assert.equal(validateBackup({meta:{schemaVersion:2}}).ok,false)});
